spring:
  datasource:
    url: jdbc:mysql://mysql.railway.internal:3306/railway
    username: root
    password: mImOcCXADLSxmrMiVeFURILZTGuODyPU

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
