spring:
  profiles:
    active: ${ENV:dev}  # Uses 'dev' as default if ENV is not set
  config:
    location: file:./config/*/
  jackson:
    date-format: dd/MM/yyyy

server:
  port: 8080
  # address: 0.0.0.0

