package com.CSIR.TMD.Entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity
@Table(name = "Section_Four")
public class SectionFour {

    @Id
    @Column(name = "technology_ref_no", length = 25, nullable = false)
    private String technologyRefNo;  // Primary key

    @Column(name = "client_name", length = 300, nullable = false)
    private String clientName;

    @Column(name = "client_address", length = 300, nullable = false)
    private String clientAddress;

    public SectionFour(String technologyRefNo, String clientName, String clientAddress, String city, String country, String nodalContactPerson, String deploymentDetails) {
        this.technologyRefNo = technologyRefNo;
        this.clientName = clientName;
        this.clientAddress = clientAddress;
        this.city = city;
        this.country = country;
        this.nodalContactPerson = nodalContactPerson;
        this.deploymentDetails = deploymentDetails;
    }

    @Column(name = "city", length = 300, nullable = false)
    private String city;

    @Column(name = "country", length = 100, nullable = false)
    private String country;

    @Column(name = "nodal_contact_person", length = 300, nullable = false)
    private String nodalContactPerson;

    @Column(name = "deployment_details", length = 300)
    private String deploymentDetails;

    public SectionFour() {
    }

    public String getTechnologyRefNo() {
        return technologyRefNo;
    }

    public void setTechnologyRefNo(String technologyRefNo) {
        this.technologyRefNo = technologyRefNo;
    }

    public String getClientName() {
        return clientName;
    }

    public void setClientName(String clientName) {
        this.clientName = clientName;
    }

    public String getClientAddress() {
        return clientAddress;
    }

    public void setClientAddress(String clientAddress) {
        this.clientAddress = clientAddress;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public String getNodalContactPerson() {
        return nodalContactPerson;
    }

    public void setNodalContactPerson(String nodalContactPerson) {
        this.nodalContactPerson = nodalContactPerson;
    }

    public String getDeploymentDetails() {
        return deploymentDetails;
    }

    public void setDeploymentDetails(String deploymentDetails) {
        this.deploymentDetails = deploymentDetails;
    }
// Getters and Setters are generated by Lombok's @Data annotation
}
